#!/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
#
# (That line is included so we don't have to launch the program
# as 'python <program>', we can just run it directly on the commandline.
# The path specified there is the path to your preferred version of
# python. How to make a python package executable on a windows machine
# is different.)
#
# merger
# 
#
import sys, os, getopt
from shutil import copytree, rmtree, copyfile

# Variable declarations
title = ""
bookDir = ""
authorFirst = "" 
authorLast = ""
chapters = []
startChapter = "<!-- Start: "
chapterFile = "<!-- File: "
endChapter = "<!-- End: -->"
idTag = "[ID]"
titleTag = "[TITLE]"
bodyTag = "[BODY]"
searchAuthor = "Firstname Lastname"
force = False

def replace(search, result, line):
	# I do this several times in the code, so hey, mod it!
	newline = line
	found = line.find(search)
	if found > -1:
		newline = line[0:found] + result + line[found + len(search):]
	return newline
	
def extract(search, line):
	# returns the juicy data, without the cruft
	if line.find(search) > -1:
		return line[line.find(search) + len(search):-len(" -->\n")] # these lines should always end " -->\n"

def doBookInfo(filepath):
	# global bookInfo
	global title
	global bookDir
	global authorFirst
	global authorLast
	with open(filepath) as fp:
		for line in fp:
			findTitle = "<!-- Title: "
			findBookDir = "<!-- BookDir: "
			findAuthorFirst = "<!-- AuthorFirst: "
			findAuthorLast = "<!-- AuthorLast: "
			if line.find(findTitle) > -1:
				title = extract(findTitle, line)
			elif line.find(findBookDir) > -1:
				bookDir = extract(findBookDir, line)
			elif line.find(findAuthorFirst) > -1:
				authorFirst = extract(findAuthorFirst, line)
			elif line.find(findAuthorLast) > -1:
				authorLast = extract(findAuthorLast, line)
	bookInfo = [title, bookDir, authorFirst, authorLast]
	
	if os.path.isdir(bookDir):
		print("Destination directory " + bookDir + " exists!")
		if force:
			print("Overwriting with -f flag.")
			rmtree(bookDir)
		else:
			print("(use the -f flag to force  in future)")
			response = input("Do you want to delete it? (y/n) ")
			if response == 'y' or response == 'Y':
				rmtree(bookDir)
			else:
				exit()
	copytree("source/book", bookDir)
	copyfile("style.css", bookDir + "/OEBPS/Styles/style.css")

def dochapters(filepath):
	global chapters
	with open(filepath) as fp:
		for line in fp: # this is going to let me look at every line in the file
			if line.find(startChapter) > -1:         # if I found something, found will be > 0
				chapterHead = extract(startChapter, line)  # great, get the string
				line = fp.readline()   # read the next line of the original file
				if line.find(chapterFile) > -1: 
					filename = extract(chapterFile, line).split()[0]
					chapterID = extract(chapterFile, line).split()[1]
					chapters.append([chapterHead, "Text/" + filename, chapterID])  
					writeFile = open(bookDir + "/OEBPS/Text/" + filename, 'w') # open it as a file to write
					templatefile = "source/blankchapter.xhtml"
					with open(templatefile) as template:
						for templine in template:
							if templine.find(idTag) > -1:
								found = templine.find(idTag)
								templine = templine[0:found] + chapterID + templine[found+4:]
							elif templine.find(titleTag) > -1:
								found = templine.find(titleTag)
								templine = templine[0:found] + chapterHead + templine[found+7:]
							else:
								if templine.find(bodyTag) > -1:
									nextline = fp.readline()
									while nextline.find(endChapter) == -1:
										writeFile.write(nextline)
										nextline = fp.readline()
									templine = ""
							writeFile.write(templine)
					writeFile.close()      # close the write file
		coverFile = "source/blankcover.xhtml"
		coverDestination = bookDir + "/OEBPS/Text/cover.xhtml"
		wf = open(coverDestination, 'w')
		with open(coverFile) as cover:
			for line in cover:
				if line.find(titleTag) > -1:
					line = replace(titleTag, title, line)
				elif line.find(searchAuthor) > -1:
					line = replace(searchAuthor, authorFirst + " " + authorLast, line)
				wf.write(line)
		wf.close()
	
def dotocxhtml():
	tocFile = "source/blanktoc.xhtml"
	tocOutFile = bookDir + "/OEBPS/Text/toc.xhtml"
	firstnameSearch = "Firstname"
	lastnameSearch = "Lastname"
	tocOut = open(tocOutFile, 'w')
	with open(tocFile) as toc:
		for line in toc:
			if line == "[TOC]\n":
				line = ""
				for each in chapters:
					tocOut.write("\t\t<li><a href=\"../" + each[1] + "\"><span>" + each[0] + "</span></a></li>\n")
			elif line.find(titleTag) > -1:
				line = line[0:line.find(titleTag)] + title + line[line.find(titleTag)+len(titleTag):]
			elif line.find(firstnameSearch) > -1:
				line = replace(firstnameSearch, authorFirst, line)
				line = replace(firstnameSearch, authorFirst, line)
				line = replace(lastnameSearch, authorLast, line)
				line = replace(lastnameSearch, authorLast, line)
			tocOut.write(line)
	chapters.insert(0,["Table of Contents", "Text/toc.xhtml", "toc"])
	tocOut.close()
					
def docontent():	
	contentFile = "source/blankcontent.opf"
	contentOutFile = bookDir + "/OEBPS/content.opf"
	contentOut = open(contentOutFile, 'w')
	with open(contentFile) as content:
		for line in content:
			if line == "[MANIFEST]\n":
				for each in chapters:
					contentOut.write("\t<item href=\"" + each[1] + "\" id=\"" + each[2] + "\" media-type=\"application/xhtml+xml\" />\n")
			elif line == "[SPINE]\n":
				for each in chapters:
					contentOut.write("\t<itemref idref=\"" + each[2] + "\" />\n")
			elif line == "[GUIDE]\n":
				for each in chapters:
					contentOut.write("\t<reference href=\"" + each [1] + "\" type=\"text\" />\n")
			elif line.find("[TITLE]") > -1:
				contentOut.write(line[0:line.find("[TITLE]")] + title + line[line.find("[TITLE]") + len("[TITLE]"):])
			else:
				contentOut.write(line)
	contentOut.close()
	
def dotocncx():
	tocFile = "source/blanktoc.ncx"
	tocOut = bookDir + "/OEBPS/toc.ncx"
	tocOut = open(tocOut, 'w')
	with open(tocFile) as toc:
		for line in toc:
			if line == "[NCX]\n":
				point = 2
				for each in chapters:
					tocOut.write("\t<navPoint id =\"" + each[2] + "\" playOrder=\"" + str(point) + "\">\n")
					tocOut.write("\t\t<navLabel>\n")
					tocOut.write("\t\t\t<text>" + each[0] + "</text>\n")
					tocOut.write("\t\t</navLabel>\n")
					tocOut.write("\t\t<content src=\"" + each[1] + "\"/>\n")
					tocOut.write("\t</navPoint>\n")
					point += 1
			else:
				tocOut.write(line)
	tocOut.close()
	
def main(argv):
	global force
	filepath = ''
	try:
		opts, args = getopt.getopt(argv, "h:i:f")
	except getopt.GetoptError:
		print("merger -i <inputfile> [-f]")
		exit(2)
	for opt, arg in opts:
		if opt == "-h":
			print("merger -i <inputfile> [-f]")
			exit()
		if opt in ("-i"):
			filepath = arg
		elif opt in ("-f"):
			force = True
	if not os.path.isfile(filepath):
	# does the file exist?
		print("File path {} does not exist. Exiting...".format(filepath))
		# if it doesn't, tell the user and quit
		exit()
	doBookInfo(filepath)
	dochapters(filepath)
	dotocxhtml()
	docontent()
	dotocncx()
	



main(sys.argv[1:]) # run the program

	
