#!/bin/bash
rm -f epub/$1.epub
cd $1
zip -q0X "../epub/$1.epub" mimetype
zip -qXr9D "../epub/$1.epub" * -x "*.svn*" -x "*~" -x "*.hg*" -x "*.swp" -x "*.DS_Store"
java -jar ../bin/epubcheck.jar ../epub/$1.epub
